services:
  backend:
    build: .
    container_name: leveyqc-backend
    restart: unless-stopped

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3308/LeveyCentral
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""

    extra_hosts:
      - "host.docker.internal:host-gateway"